tap 'caskroom/cask'
tap 'homebrew/services'

brew 'bash'
brew 'git'
brew 'reattach-to-user-namespace'
brew 'stow'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'vim'
brew 'zplug'
brew 'zsh'

cask '1password'
cask 'alfred'
cask 'caffeine'
cask 'flux'
cask 'google-chrome'
cask 'karabiner'
cask 'macvim'
cask 'slack'
cask 'sourcetree'
cask 'spectacle'
cask 'spotify'
