#!/bin/sh

colors() {
  printf %s '   '
  for color in "$@"; do
    tput setab ${color}
    printf %s '   '
  done
  tput sgr0
  echo
}

echo

colors 8 9 10 11 12 13 14 15
colors 8 9 10 11 12 13 14 15
colors 8 9 10 11 12 13 14 15
colors 0 1 2 3 4 5 6 7

echo
