#!/bin/sh
# Thank you: https://github.com/chrishunt/dot-files

set -e

echo "      _       _         __ _ _"
echo "   __| | ___ | |_      / _(_) | ___  ___"
echo "  / _\` |/ _ \| __|____| |_| | |/ _ \/ __|"
echo " | (_| | (_) | ||_____|  _| | |  __/\__ \\"
echo "  \__,_|\___/ \__|    |_| |_|_|\___||___/"
echo ""

echo "==> Here we go..."

echo "  > Installing homebrew..."
if command -v brew >/dev/null 2>&1; then
  echo "    > (Skipping) Already installed."
else
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" &> /dev/null
fi

echo "  > Updating homebrew..."
brew update &> /dev/null

echo "  > Pulling latest dot-files..."
cd $HOME/.dotfiles && git pull &> /dev/null

echo "  > Setting up colors..."
echo "      > Setting up zsh..."
cp $HOME/.dotfiles/colorschemes/dracula.zsh-theme $HOME/.oh-my-zsh/themes/
echo "      > Setting up vim..."
cp $HOME/.dotfiles/colorschemes/dracula.vim $HOME/.vim/colors/
echo "  > To set up iTerm colors, run:"
echo "  $ open ./colorschemes/Dracula.itermcolors"

echo "  > To install homebrew packages, run:"
echo "  $ ./brewfile.sh"

echo "==> Done with setup."
