#!/usr/bin/env bash
# Thank you: https://github.com/chrishunt/dot-files

set -e

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

echo "==> Here we go..."

echo "  > Installing homebrew..."
if command -v brew >/dev/null 2>&1; then
  echo "    > (Skipping) Already installed."
else
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" &> /dev/null
fi

echo "  > Updating homebrew..."
brew update

echo "  > Pulling latest dot-files..."
cd $HOME/.dotfiles && git pull &> /dev/null

echo "  > Installing brews..."
brew install $(cat Brewfile|grep -v "#")

echo "  > Installing casks..."
brew cask install $(cat Caskfile|grep -v "#")

echo "  > Setting up fish shell..."
echo "/usr/local/bin/fish" | sudo tee -a /etc/shells
chsh -s /usr/local/bin/fish

echo "==> Done with setup."
